force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SDLC_BuildControllerTest.cls
/*
*********************************************************
@Class Name      : SDLC_BuildController
@TestClassName   : SDLC_BuildControllerTest
@author          : COE Team - Sachin(1347061)
@description     : This class covers test coverage of the methods of SDLC_BuildController Class
********************************************************
*/

@isTest
private class SDLC_BuildControllerTest {
    
    @testSetup static void createData() {
        
        // Create test data 
        Engagement__c engObj = SDLC_TestDataFactory.createEngagement();
        Portfolio__c portObj = SDLC_TestDataFactory.createPortfolio(engObj.Id);
        Product__c productObj = SDLC_TestDataFactory.createProduct(portObj.Id);
        Epic__c epicObj = SDLC_TestDataFactory.createEpic(productObj.Id);
        List<UserStory__c> userStories = SDLC_TestDataFactory.createUserStories(epicObj.Id,5);
        SDLC_TestDataFactory.insert_ComponentSpecAndJunctionRecord(userStories,'Test Response');
        
    }
    
    @isTest
    static void testGetUserStoriesData_WithRecords() {
        
        // Call the method to test
        List<Map<String, Object>> dataMap = SDLC_BuildController.getUserStoriesData([SELECT Id FROM Epic__c LIMIT 1].Id);
        
        // Perform assertions
        System.assertNotEquals(0, dataMap.size(), 'Expected data map to have records');
    }
    
    @isTest
    static void testGetUserStoriesData_WithNoRecords() {
        
        // Call the method to test
        List<Map<String, Object>> dataMap = SDLC_BuildController.getUserStoriesData('NonExistingEpicId');
        
        // Perform assertions
        System.assertEquals(0, dataMap.size(), 'Expected data map to have records');
    }
    
}