force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>CMT</fullName>
                <label>Communications</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/ModelName__c.field-meta.xml
<CustomField>
    <fullName>ModelName__c</fullName>
    <label>LLM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EinsteinGPT</fullName>
            </value>
            <value>
                <fullName>OpenAI ChatGPT</fullName>
            </value>
            <value>
                <fullName>AzureGPT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/OutputQuality__c.field-meta.xml
<CustomField>
    <fullName>OutputQuality__c</fullName>
    <label>Output Quality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Excellent</fullName>
            </value>
            <value>
                <fullName>Average</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/OutputType__c.field-meta.xml
<CustomField>
    <fullName>OutputType__c</fullName>
    <label>Output Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>VF Page</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>SOQL</fullName>
            </value>
            <value>
                <fullName>User Story</fullName>
            </value>
            <value>
                <fullName>Dataflow Diagram</fullName>
            </value>
            <value>
                <fullName>Business Requirements Document</fullName>
            </value>
            <value>
                <fullName>High Level Design Document</fullName>
            </value>
            <value>
                <fullName>Component Design Document</fullName>
            </value>
            <value>
                <fullName>Sequence Diagram</fullName>
            </value>
            <value>
                <fullName>Wireframe</fullName>
            </value>
            <value>
                <fullName>Test Plan</fullName>
            </value>
            <value>
                <fullName>Test Class</fullName>
            </value>
            <value>
                <fullName>Test Case</fullName>
            </value>
            <value>
                <fullName>Functional Description</fullName>
            </value>
            <value>
                <fullName>Technical Description</fullName>
            </value>
            <value>
                <fullName>DML Statements</fullName>
            </value>
            <value>
                <fullName>SOQL Statements</fullName>
            </value>
            <value>
                <fullName>Code Quality Assessment</fullName>
            </value>
            <value>
                <fullName>Package XML</fullName>
            </value>
            <value>
                <fullName>Release Notes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Optimize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/PromptComplexity__c.field-meta.xml
<CustomField>
    <fullName>PromptComplexity__c</fullName>
    <label>Prompt Complexity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Complex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/PromptType__c.field-meta.xml
<CustomField>
    <fullName>PromptType__c</fullName>
    <label>Prompt Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Engineering</fullName>
            </value>
            <value>
                <fullName>Business Capability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PromptLibraryController.cls
public with sharing class PromptLibraryController {

    @AuraEnabled
    public static List<PromptLibrary__c> getPromptListWithFilters(Map<String,String> filterVariables){
        List<PromptLibrary__c> promptFilteredList= new List<PromptLibrary__c>();

        String query = 'Select Id, Name, Prompt__c, PromptType__c,Phase__c, Entity__c, Industry__c, OutputType__c, ModelName__c, PromptComplexity__c, OutputQuality__c FROM PromptLibrary__c WHERE Name != null';
        for(String params : filterVariables.keySet()){
            if(params != null && filterVariables.get(params) != 'All'){
                query += ' AND '+params+' = '+ '\''+filterVariables.get(params)+'\'';
            }
            else if(filterVariables.get(params) == 'All'){
                continue;
            }
        }
        query+= ' ORDER BY Name ASC';
        System.debug('Gokul query line '+query);
        promptFilteredList = Database.query(query);
        

        return promptFilteredList;
    }


    @AuraEnabled
    public static List<PromptLibrary__c> createPromptImportRecords(String base64Data) {
        String data = JSON.deserializeUntyped(base64Data).toString();
        List<PromptLibrary__c> promptList = new List<PromptLibrary__c>();
        List<String> lstCSVLines = data.split('\n');
        for(Integer i = 1; i < lstCSVLines.size(); i++){
            PromptLibrary__c promptLib = new PromptLibrary__c();
            String csvLine = lstCSVLines[i];
            String prevLine = csvLine;
            Integer startIndex;
            Integer endIndex;
            
            while(csvLine.indexOf('"') > -1){
                if(startIndex == null){
                    startIndex = csvLine.indexOf('"');
                    csvLine = csvLine.substring(0, startIndex) + ':quotes:' + csvLine.substring(startIndex+1, csvLine.length());
                }else{
                    if(endIndex == null){
                        endIndex = csvLine.indexOf('"');
                        csvLine = csvLine.substring(0, endIndex) + ':quotes:' + csvLine.substring(endIndex+1, csvLine.length());
                    }
                }
                
                if(startIndex != null && endIndex != null){
                    String sub = csvLine.substring(startIndex, endIndex);
                    sub = sub.replaceAll(',', ':comma:');
                    csvLine = csvLine.substring(0, startIndex) + sub + csvLine.substring(endIndex, csvLine.length());
                    startIndex = null;
                    endIndex = null;
                }
            }
            
            List<String> csvRowData = new List<String>();
            for(String column : csvLine.split(',')){
                column = column.replaceAll(':quotes:', '').replaceAll(':comma:', ',');
                csvRowData.add(column);
            }
            System.debug('Gokul Datareceived : '+csvRowData);
            promptLib.Prompt__c = csvRowData[0];
            promptLib.PromptType__c = csvRowData[1];
            promptLib.Entity__c = csvRowData[2];
            promptLib.Industry__c = csvRowData[3];
            promptLib.OutputType__c = csvRowData[4];
            promptLib.ModelName__c = csvRowData[5];
            promptLib.PromptComplexity__c = csvRowData[6];
            promptLib.OutputQuality__c = csvRowData[7];
            promptLib.Phase__c = csvRowData[8];
            promptList.add(promptLib);
        }
        if(!promptList.isEmpty()){
            insert promptList;
        }
        return promptList;
    }


    @AuraEnabled
    public static String executePrompt(String prompt,String context){

        List<Object> promptList = new List<Object>();
        AIHelper.addPrompt(promptList,'system','Hi, I am your Prompt Engineer Assistant.');
        AIHelper.addPrompt(promptList,'user',context);
        AIHelper.addPrompt(promptList,'user',prompt);
        String requestBody=AIHelper.createRequestBody(promptList);

        HttpRequest req=AIHelper.createHTTPRequest();
        req.setBody(requestBody);

        try{
            HttpResponse response = new Http().send(req);
            system.debug('response '+ response.getBody());
            if(response.getStatusCode() == 200) {
            return AIHelper.extractResponse(response.getBody());
            } else if(response.getStatusCode() == 503) {
                return 'Error';
            }
            else{
                return 'Error';
            }
        }catch(Exception e){
            return 'Error';
        }
       
    }
}