force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ActionButtonController.cls
public with sharing class ActionButtonController {
    
    @AuraEnabled
    public static void updateUserStoryToAwaitingApproval(Id recordId){

        UserStory__c currentUserStory = [Select Id, Status__c FROM UserStory__c
                                                WHERE Id=: recordId LIMIT 1];

        if(currentUserStory.Status__c !='Draft'){
            return;
        }
        currentUserStory.Status__c = 'Awaiting Approval';
        update currentUserStory;
    }

    @AuraEnabled
    public static void updateUserStoryToApprove(Id recordId){

        UserStory__c currentUserStory = [Select Id, Status__c FROM UserStory__c
                                                WHERE Id=: recordId LIMIT 1];

        if(currentUserStory.Status__c !='Awaiting Approval'){
            return;
        }
        currentUserStory.Status__c = 'Approved';
        update currentUserStory;
    }
}