force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationTable__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Library</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>PromptLibrary__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/Sub_Action_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Action_Name__c</fullName>
    <label>Sub Action Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LLM__c/LLM__c.object-meta.xml
<CustomObject>
    <label>LLM</label>
    <nameField>
        <label>LLM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Optimize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SDLC_ConfigTableController.cls
/*
*********************************************************
@Class Name      : SDLC_ConfigTableController
@author          : COE - Sachin(1347061) 
@description     : This class handles various functionalities related to Build Phase of Configuration Table save and update
******************************************************************************
*/
public with sharing class SDLC_ConfigTableController {
    
        /*
*********************************************************
@Method Name     : updateConfigTable
@author          : COE Team - Sachin[1347061]
@description     : Get Config Table Records Date and group them to show on UI/UX
@param inputType : configDataMap as an JSON Object
@return          : True or false
********************************************************
*/ 
    
    @AuraEnabled
    public static boolean updateConfigTable(List<Map<String, Object>> configDataMap) {
        system.debug('configDataMap-->'+configDataMap);
        if(configDataMap != Null && !configDataMap.isEmpty()){}
        return false;
    }
    
    /*
*********************************************************
@Method Name     : getConfigTableData
@author          : COE Team - Sachin[1347061]
@description     : Get Config Table Records Date and group them to show on UI/UX
@param inputType : Void
@return          : JSON Data object
********************************************************
*/ 
    @AuraEnabled
    public static List<Map<String, Object>> getConfigTableData(){
        
        
        String key = '';
        String configData = 'Error while Fetching Configuration Table';
        List<Map<String, Object>> dataMap = new  List<Map<String, Object>>();
        map<String,List<Map<String, Object>>> totalOptionsMap = New Map<String,List<Map<String, Object>>>();
        map<String,llmoptions> defaultOptions = New Map<String,llmoptions>();
        // Key = Phase + action + subActionName
        Map<String,ConfigurationTable__c> ConfigTableMap = new Map<String,ConfigurationTable__c>();
        
        List<ConfigurationTable__c> configTableList = [SELECT Id, Name, Action__c, Active__c, Phase__c, LLM__c,LLM__r.Name, PromptLibrary__c, Prompt_With_Explanation__c, Sub_Action_Name__c, Action_Name__c
                                                       FROM ConfigurationTable__c Order By Phase__c ASC];
        if(configTableList.size()>0){
            for(ConfigurationTable__c thisRecord :configTableList ){
                Key = (String) thisRecord.Phase__c +  thisRecord.Action__c +  thisRecord.Sub_Action_Name__c; 
                
                if(thisRecord.LLM__c != Null &&  !totalOptionsMap.ContainsKey(Key)){
                    Map<String, Object> totaloption = new Map<String, Object>();
                    totaloption.put('label',thisRecord.LLM__r.Name);
                    totaloption.put('value',thisRecord.LLM__r.Name);
                    totalOptionsMap.put(Key,new List<Map<String, Object>>{totaloption});
                }else if(thisRecord.LLM__c != Null && totalOptionsMap.ContainsKey(Key)){
                    Map<String, Object> totaloption = new Map<String, Object>();
                    totaloption.put('label',thisRecord.LLM__r.Name);
                    totaloption.put('value',thisRecord.LLM__r.Name);
                    totalOptionsMap.get(Key).add(totaloption);
                }
                
                if(!ConfigTableMap.ContainsKey(Key) && thisRecord.Active__c){
                    ConfigTableMap.put(Key, thisRecord);
                    
                    llmoptions defaultoption = new llmoptions();
                    defaultoption.label = thisRecord.LLM__r.Name;
                    defaultoption.value = thisRecord.LLM__r.Name;
                    defaultOptions.put(Key,defaultoption);
                    
                }
            }
            
            if(!ConfigTableMap.IsEmpty()){
                
                for(String thiskey : ConfigTableMap.keySet()){
                    
                    Map<String, Object> summaryMap = new Map<String, Object>(); 
                    summaryMap.put('id', ConfigTableMap.get(thiskey).Id);
                    summaryMap.put('formattedKey', thiskey);
                    summaryMap.put('phase', ConfigTableMap.get(thiskey).Phase__c);
                    summaryMap.put('category', ConfigTableMap.get(thiskey).Action__c);
                    summaryMap.put('subCategory', ConfigTableMap.get(thiskey).Sub_Action_Name__c);
                    summaryMap.put('llmoptions', totalOptionsMap.get(thiskey));
                    summaryMap.put('llm', defaultOptions.get(thiskey).value);
                    summaryMap.put('popularity','90%');
                    summaryMap.put('rating', '4');
                    dataMap.add(summaryMap);
                }
                
                
            }
        }
        return dataMap;
    }
    
    class llmoptions {
        public String label;	//GPT3.5 Turbo
        public String value;	//GPT3.5 Turbo
    }
}