force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationTable__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Library</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>PromptLibrary__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LLM__c/LLM__c.object-meta.xml
<CustomObject>
    <label>LLM</label>
    <nameField>
        <label>LLM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SDLC_InfyAIForceUtility_Test.cls
@isTest
public with sharing class SDLC_InfyAIForceUtility_Test {
    @isTest
    static void testGetCurrentUserLicenseData() {
        User tesUser = SDLC_TestDataFactory.createStandardUser();
        //User testUser = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        Test.startTest();
        List<User> userList = SDLC_InfyAIForceUtility.getCurrentUserLicenseData();
        Test.stopTest();

        System.assertEquals(1, userList.size(), 'User list size should be 1');
        System.assertEquals('005P000000CdQhXIAV', '005P000000CdQhXIAV', 'User Ids should match');
    }

    @isTest
    static void testGetAllUserLicenses() {
        Test.startTest();
        List<PermissionSetLicense> licenseList = SDLC_InfyAIForceUtility.getAllUserLicesnse();
        Test.stopTest();

        System.assertNotEquals(null, licenseList, 'License list should not be null');
        System.assertEquals(8, licenseList.size(), 'License list size should be 8'); // Assuming 8 licenses are added in the test method
    }

    @isTest
    static void testGetAllEngagementSuccess() {
               Test.startTest();
        // Setup test data for the successful scenario
        List<Engagement__c> testEngagements = new List<Engagement__c>();
        for (Integer i = 0; i < 500; i++) {
            testEngagements.add(new Engagement__c(Name = 'Engagement ' + i));
        }
        insert testEngagements;

        // Call the method
        List<Engagement__c> engagements = SDLC_InfyAIForceUtility.getAllEngagement();

        // Add assertions to verify the data returned or any other expected behavior
        System.assertNotEquals(null, engagements, 'Engagements list should not be null');
        System.assertEquals(500, engagements.size(), 'Expected 500 engagements');
        Test.stopTest();
    }

    @isTest
    static void testGetAllEngagementException() {
        Test.startTest();
        try {
            List<Engagement__c> engagements = SDLC_InfyAIForceUtility.getAllEngagement();
        } catch (AuraHandledException e) {
            System.assertEquals('An error occurred while fetching engagements.', e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void testGetAllPortfolios() {
        String engagementId = 'a0JKR000000KzO12AK'; 
        Test.startTest();
        List<Portfolio__c> portfolioList = SDLC_InfyAIForceUtility.getAllPortfolios(engagementId);
        Test.stopTest();
    }

    @isTest
    static void testGetAllProductDetails() {
        String portfolioId = 'a0KKR000000NeSx2AK'; 
        Test.startTest();
        List<Product__c> productList = SDLC_InfyAIForceUtility.getAllProductDetails(portfolioId);
        Test.stopTest();

    }

    @isTest
    static void testGetAllEpicDetails() {
        String productId = 'a0NKR000000Gmmt2AC'; 
        Test.startTest();
        List<Epic__c> epicList = SDLC_InfyAIForceUtility.getAllEpicDetails(productId);
        Test.stopTest();

    }

    @isTest
    static void testProcessCSV() {
        String csvData = 'sample,data,for,testing';
        String processedData = SDLC_InfyAIForceUtility.processCSV(csvData);
        System.assertEquals(csvData, processedData, 'Processed data should match original CSV data');
    }

    @isTest
    static void testExecuteLLM() {
        SDLC_TestDataFactory.createConfigurationTable();
        ConfigurationTable__c config = [Select Id, LLM__c, PromptLibrary__c FROM ConfigurationTable__c LIMIT 1];
        String inputType = 'Custom';
        String userInput = 'generate user stories from below input';
        Object inputFile = null;
        String configId = config.Id; 
        String className = 'LLMOpenAI'; 

        Test.startTest();
        String llmResponse = SDLC_InfyAIForceUtility.executeLLM(inputType, userInput, inputFile, configId, className);
        Test.stopTest();
       // System.assertNotEquals(null, llmResponse, 'LLM response should not be null');
    }

    @isTest
    static void testFormatInputLLM() {
        String inputType = 'Custom';
        String userInput = 'As a user I want to set a deadline for the opportunity to ensure timely follow-up and action';
        Object inputFile = null;
        
        String customContext = SDLC_InfyAIForceUtility.formatInputLLM(inputType, userInput, inputFile);
        System.assertEquals(userInput, customContext, 'Custom input type should return the user input');
        
        inputType = 'CSV';
        String csvData = 'CSVData'; 
        inputFile = csvData;
        String csvContext = SDLC_InfyAIForceUtility.formatInputLLM(inputType, userInput, inputFile);
        System.assertEquals('CSVData', csvContext, 'CSV input type should return processed CSV data');
        
        inputType = 'JSON';
        Map<String, Object> jsonMap = new Map<String, Object>{
            'title' => 'Sample.doc',
            'versionData' => Blob.valueOf('Sample Document Content')
        };
        inputFile = jsonMap;
        
        Test.startTest();
        String jsonContext = SDLC_InfyAIForceUtility.formatInputLLM(inputType, userInput, inputFile);
        //System.assertEquals('U2FtcGxlIERvY3VtZW50IENvbnRlbnQ=', jsonContext, 'JSON input type should return base64 encoded data for .doc files');
        Test.stopTest();
    }

    @isTest
    static void testExecutePrompt() {
        String prompt = 'generate 5 user stories from below input';
        String inputType = 'Custom';
        String userInput = 'As a user, I want to set a deadline for the opportunity to ensure timely follow-up and action.';
        Object inputFile = null; 

        // Set up mock HTTP response
        Test.setMock(HttpCalloutMock.class, new SDLC_MockHttpResponseGenerator_Test());

        Test.startTest();
        String result = SDLC_InfyAIForceUtility.executePrompt(prompt, inputType, userInput, inputFile);
        Test.stopTest();

        System.assertEquals(result , result);
    }

    @IsTest
    static void testExecutePromptCSVInput() {
        String prompt = 'generate user stories from below input';
        String inputType = 'CSV';
        String userInput = null; 
        Object inputFile = 'As a user I want to set a deadline for the opportunity to ensure timely follow-up and action, As a user I want to set a deadline for the opportunity to ensure timely follow-up and action'; // Sample CSV file data

        String result = SDLC_InfyAIForceUtility.executePrompt(prompt, inputType, userInput, inputFile);

        System.assertEquals(result , result);
    }

   /* @IsTest
    static void testExecutePrompt_OtherInput() {
        // Prepare test data
        String prompt = 'generate user stories from below input';
        String inputType = 'Other';
        String userInput = null; // Not used for other input types
        Object inputFile = 'As a user I want to set a deadline for the opportunity to ensure timely follow-up and action';

        // Call the method
        String result = SoftwateEngOptimizerUtilityController.executePrompt(prompt, inputType, userInput, inputFile);

        // Assert the result
        System.assertEquals(result , result);
    }*/
}