force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationTable__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Library</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>PromptLibrary__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LLM__c/LLM__c.object-meta.xml
<CustomObject>
    <label>LLM</label>
    <nameField>
        <label>LLM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LLM__c/fields/NameCred__c.field-meta.xml
<CustomField>
    <fullName>NameCred__c</fullName>
    <label>Name Cred</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LLMOpenAI.cls
public class LLMOpenAI implements LLMInterface{

    String payload;
    HttpResponse response;
    String endPoint;
    String namedCredential;
    
    List<Object> promptList;
    String model;
    String context;
    String prompt;
    Id configId;

    
    public LLMOpenAI(){
        this.model='gpt-3.5-turbo';
        this.namedCredential='Chatgpt';
        this.context='I am a Salesforce admin';
        this.prompt='How do I become developer?';
    }
    String getEndPoint(){
        return 'callout:'+this.namedCredential;
      
    }

    public void setLLMConfigId(Id configId){
        this.configId=configId;
        getConfigurationDetails(configId);
    }

    public void setPromptContext(Object input){
        this.context=JSON.serialize(input);
        system.debug('INPUT '+this.context);
    }
    
    public void buildPayload(){
        
        List<Object> promptList = new List<Object>();
        AIHelper.addPrompt(promptList,'system','Hi, I am your SOftware Engineering Assistant.');
        AIHelper.addPrompt(promptList,'user',this.context);
        AIHelper.addPrompt(promptList,'user',this.prompt);
        
        Map<String,Object> prompRequestBody = new Map<String,Object>();
        prompRequestBody.put('messages',promptList);
        prompRequestBody.put('model',model);
        
  
        this.payload=JSON.serialize(prompRequestBody);
       
    }
    public void callLLM(){
        HttpRequest request = new HttpRequest();
        request.setEndpoint(this.getEndPoint());
        request.setMethod('POST');
        request.setTimeout(120000);
        request.setHeader('Content-Type', 'application/json');
        
        request.setBody(this.payload);
        response=new Http().send(request);
    }
    public String processResponse(){

         Map<String, Object> responseBody = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
     	 System.debug(response.getBody());
        List<Object> choices = (List<Object>)responseBody.get('choices');
        if (choices.size() > 0) {
            Map<String, Object> choice = (Map<String, Object>)choices.get(0);
            Map<String,Object> mpMessages = (Map<String,Object>)choice.get('message');
            String responseText = (String)mpMessages.get('content');
            responseText = responseText != null ? responseText.trim() : '';
            return responseText;
        }else{
            return 'error';
        }   
    }

    public void getConfigurationDetails(Id configId){

        ConfigurationTable__c config = [Select Id
                                                , Name
                                                , LLM__r.Name
                                                , LLM__r.Id
                                                , LLM__r.NameCred__c
                                                , LLM__r.Model__c
                                                , LLM__r.ClassName__c
                                                , PromptLibrary__r.Id
                                                , PromptLibrary__r.Prompt__c
                                            FROM ConfigurationTable__c 
                                            WHERE Id=:configId
                                            LIMIT 1];

        this.namedCredential = config.LLM__r.NameCred__c;
        this.model = config.LLM__r.Model__c;
        this.prompt = config.PromptLibrary__r.Prompt__c;
        
    }
}