force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationTable__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Library</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>PromptLibrary__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LLM__c/LLM__c.object-meta.xml
<CustomObject>
    <label>LLM</label>
    <nameField>
        <label>LLM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LLM__c/fields/NameCred__c.field-meta.xml
<CustomField>
    <fullName>NameCred__c</fullName>
    <label>Name Cred</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Optimize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/AcceptanceCriteria__c.field-meta.xml
<CustomField>
    <fullName>AcceptanceCriteria__c</fullName>
    <label>Acceptance Criteria</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/ComponentSpec__c.field-meta.xml
<CustomField>
    <fullName>ComponentSpec__c</fullName>
    <label>Component Spec</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SDLC_AnalysisController.cls
/**
 * @description       : 
 * @author            : Gokul Sriram
 * @group             : 
 * @last modified on  : 03-21-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class SDLC_AnalysisController {

    @AuraEnabled
    public static void insertUserStories(List<UserStoryWrapper> userStoryList, String epicId) {
        List<UserStory__c> userStoryToInsert = new List<UserStory__c>();
        for(UserStoryWrapper userStoryWrapper : userStoryList) {
            UserStory__c userStory = new UserStory__c();
            userStory.Title__c = userStoryWrapper.title;
            userStory.User_Story__c = userStoryWrapper.userStory;
            userStory.AcceptanceCriteria__c = userStoryWrapper.acceptanceCriteria;
            userStory.Epic__c = epicId; 
            
            if (Schema.sObjectType.UserStory__c.isCreateable()) {
                userStoryToInsert.add(userStory);
            } else {
                system.debug('Insufficient create permission for UserStory__c');
            }
        }

        if(!userStoryToInsert.isEmpty()){
            insert userStoryToInsert;
        }else{
            system.debug('No user stories to insert');
        }
    }

    @AuraEnabled
    public static List<UserStoryWrapper> getSavedUserStories(String epicId){
        system.debug('generate-epicId==>'+epicId);
        if(epicId!=''){
            List<UserStory__c> userStoryList = [SELECT Id,name, Title__c,User_Story__c, AcceptanceCriteria__c,ComponentSpec__c FROM UserStory__c Where Epic__c=:epicId  WITH USER_MODE Order By CreatedDate Desc Limit 1000];
            List<UserStoryWrapper> userStoryWrapperList = new List<UserStoryWrapper>();
            for(UserStory__c userStory : userStoryList) {
                UserStoryWrapper userStoryWrapper = new UserStoryWrapper();
                userStoryWrapper.title = userStory.Title__c;
                userStoryWrapper.acceptanceCriteria = userStory.AcceptanceCriteria__c;
                userStoryWrapper.name = userStory.name+'-'+userStoryWrapper.title;
                userStoryWrapper.Id = userStory.Id;
                userStoryWrapper.userStory = userStory.User_Story__c;
                userStoryWrapper.componentSpec = userStory.ComponentSpec__c;
                userStoryWrapperList.add(userStoryWrapper);
            }
            system.debug('userStoryWrapperList==> '+userStoryWrapperList);
            return userStoryWrapperList;
        }
        else{
            return null;
        }
    }
   
    /*Create a wrapper class for User Story with two fields title and AcceptanceCriteria*/
    public class UserStoryWrapper {
        @AuraEnabled
        public String title { get; set; }
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public String userStory { get; set; }
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled
        public String acceptanceCriteria { get; set; }
        @AuraEnabled
        public String componentSpec { get; set; }
    }


    /*
    *********************************************************
    @Method Name    : getConfigurationDetails
    @author         : Gokul
    @description    : method used to fetch configuration details
    @param          : phase type
    @return         : List<ConfigurationWrapper>
    ********************************************************
    */
    @AuraEnabled(cacheable=true)
    public static List<ConfigurationWrapper> getConfigurationDetails(String phase){

        List<ConfigurationWrapper> configurationWrapperList = new List<ConfigurationWrapper>();
        List<ConfigurationTable__c> configList = [Select Id
                                                        , Name
                                                        , LLM__r.Name
                                                        , LLM__r.Id
                                                        , LLM__r.NameCred__c
                                                        , LLM__r.Model__c
                                                        , LLM__r.ClassName__c
                                                        , PromptLibrary__r.Id
                                                        , PromptLibrary__r.Prompt__c
                                                    FROM ConfigurationTable__c 
                                                    WHERE Phase__c =:phase WITH USER_MODE];
                                                    
        for(ConfigurationTable__c config: configList){
            ConfigurationWrapper wrapper = new ConfigurationWrapper();
            wrapper.configId = config.Id;
            wrapper.configName = config.Name;
            wrapper.promptId = config.PromptLibrary__r.Id;
            wrapper.llmId = config.LLM__r.Id;
            wrapper.llmClassName = config.LLM__r.ClassName__c;
            configurationWrapperList.add(wrapper);
        }

        return configurationWrapperList;
    }
    
    public class ConfigurationWrapper{

        @AuraEnabled public String configName;
        @AuraEnabled public String prompt;
        @AuraEnabled public String promptId;
        @AuraEnabled public String namedCredential;
        @AuraEnabled public String llm;
        @AuraEnabled public String llmId;
        @AuraEnabled public String llmModel;
        @AuraEnabled public String llmClassName;
        @AuraEnabled public String configId;
    }
}