force-app/main/default/objects/ComponentSpecification__c/ComponentSpecification__c.object-meta.xml
<CustomObject>
    <label>Component Specification</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Component Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComponentSpecification__c/fields/FormattedSpecification__c.field-meta.xml
<CustomField>
    <fullName>FormattedSpecification__c</fullName>
    <label>Formatted Specification</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ComponentSpecification__c/fields/Related_User_Stories__c.field-meta.xml
<CustomField>
    <fullName>Related_User_Stories__c</fullName>
    <label>Related User Stories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Stories_Component_Spec__c/User_Stories_Component_Spec__c.object-meta.xml
<CustomObject>
    <label>User Stories Component Specs</label>
    <nameField>
        <displayFormat>US-CS-{0000}</displayFormat>
        <label>User Stories Component Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories Component Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stories_Component_Spec__c/fields/Component_Specification__c.field-meta.xml
<CustomField>
    <fullName>Component_Specification__c</fullName>
    <label>Component Specification</label>
    <referenceTo>ComponentSpecification__c</referenceTo>
    <relationshipLabel>User Stories Component Specs</relationshipLabel>
    <relationshipName>User_Stories_Component_Specs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stories_Component_Spec__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>UserStory__c</referenceTo>
    <relationshipLabel>Component Specs</relationshipLabel>
    <relationshipName>User_Stories_Component_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/Component_Specification__c.field-meta.xml
<CustomField>
    <fullName>Component_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component Specification</label>
    <referenceTo>ComponentSpecification__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SDLC_DesignController.cls
/*
*********************************************************
@Class Name      : SDLC_BuildController
@author          : COE Team - Sachin(1347061)
@description     : This class handles various functionalities related to Design Phase
********************************************************
*/
public with sharing class SDLC_DesignController {
    /*
    *********************************************************
    @Method Name     : insertComponentSpecificationRecord
    @author          : COE - Sachin
    @description     : Insert Component spec for user stories and create Junction Object
    @param prompt    : The prompt to execute.
    @param inputType : user Story Ids and Formatted Component Spec (HTML)
    @return          : True if Dml insertion of records else false
    ********************************************************
    */ 
    @AuraEnabled
    public static Boolean insertComponentSpecificationRecord(List<String> userStoryIds, String formattedResponse){
        
        String relatedStories='';
        List<User_Stories_Component_Spec__c> usComSpecToUpdateList = New List<User_Stories_Component_Spec__c>();

        List<UserStory__c> userStoryList = [SELECT Id, Name, Title__c
                                            FROM UserStory__c
                                            WHERE Id=:userStoryIds LIMIT 200];
        
        for(UserStory__c currentStory : userStoryList){
            relatedStories += currentStory.Name +'-'+currentStory.Title__c +';';
        }
        
        ComponentSpecification__c compSpec = new ComponentSpecification__c();
        compSpec.Related_User_Stories__c = relatedStories;
        compSpec.FormattedSpecification__c = formattedResponse;
        
        try{
            insert compSpec;
            //CODE TO CREATE JUCTION OBJECT : 19-03-2024
            for(UserStory__c currentStory : userStoryList){
                User_Stories_Component_Spec__c junctionObj = New User_Stories_Component_Spec__c();
                junctionObj.Component_Specification__c = compSpec.Id;
                junctionObj.User_Story__c = currentStory.Id;
                usComSpecToUpdateList.add(junctionObj);
            }
            if(usComSpecToUpdateList.size()>0){
                Insert usComSpecToUpdateList;
                return true;
            }   
        }
        catch(Exception e){
            return false;
        }

        return false;
    }
}