force-app/main/default/objects/ComponentSpecification__c/ComponentSpecification__c.object-meta.xml
<CustomObject>
    <label>Component Specification</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Component Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComponentSpecification__c/fields/FormattedSpecification__c.field-meta.xml
<CustomField>
    <fullName>FormattedSpecification__c</fullName>
    <label>Formatted Specification</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ComponentSpecification__c/fields/Related_User_Stories__c.field-meta.xml
<CustomField>
    <fullName>Related_User_Stories__c</fullName>
    <label>Related User Stories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationTable__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Library</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Phase__c</field>
            <operation>equals</operation>
            <valueField>PromptLibrary__c.Phase__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Configuration Tables</relationshipLabel>
    <relationshipName>Configuration_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/LLM__c.field-meta.xml
<CustomField>
    <fullName>LLM__c</fullName>
    <label>LLM</label>
    <referenceTo>LLM__c</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/PromptLibrary__c.field-meta.xml
<CustomField>
    <fullName>PromptLibrary__c</fullName>
    <label>Prompt Library</label>
    <referenceTo>PromptLibrary__c</referenceTo>
    <relationshipLabel>Feedback</relationshipLabel>
    <relationshipName>Feedback</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LLM__c/LLM__c.object-meta.xml
<CustomObject>
    <label>LLM</label>
    <nameField>
        <label>LLM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LLMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LLM__c/fields/NameCred__c.field-meta.xml
<CustomField>
    <fullName>NameCred__c</fullName>
    <label>Name Cred</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/PromptLibrary__c.object-meta.xml
<CustomObject>
    <label>Prompt Library</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Prompt Library Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptLibrary__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analysis</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Optimize</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromptLibrary__c/fields/PromptType__c.field-meta.xml
<CustomField>
    <fullName>PromptType__c</fullName>
    <label>Prompt Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Engineering</fullName>
            </value>
            <value>
                <fullName>Business Capability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Stories_Component_Spec__c/User_Stories_Component_Spec__c.object-meta.xml
<CustomObject>
    <label>User Stories Component Specs</label>
    <nameField>
        <displayFormat>US-CS-{0000}</displayFormat>
        <label>User Stories Component Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories Component Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Stories_Component_Spec__c/fields/Component_Specification__c.field-meta.xml
<CustomField>
    <fullName>Component_Specification__c</fullName>
    <label>Component Specification</label>
    <referenceTo>ComponentSpecification__c</referenceTo>
    <relationshipLabel>User Stories Component Specs</relationshipLabel>
    <relationshipName>User_Stories_Component_Specs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Stories_Component_Spec__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>UserStory__c</referenceTo>
    <relationshipLabel>Component Specs</relationshipLabel>
    <relationshipName>User_Stories_Component_Specs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/AcceptanceCriteria__c.field-meta.xml
<CustomField>
    <fullName>AcceptanceCriteria__c</fullName>
    <label>Acceptance Criteria</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/Component_Specification__c.field-meta.xml
<CustomField>
    <fullName>Component_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component Specification</label>
    <referenceTo>ComponentSpecification__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SDLC_TestDataFactory.cls
@isTest
public class SDLC_TestDataFactory {

    public static User createStandardUser() {
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User testUser = new User(
            Alias = 'standt',
            Email = 'testData@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'testData@testorg.com',
            ProfileId = userProfile.Id
        );
        
        insert testUser;
        return testUser;
    }

    public static Engagement__c createEngagement(){
        
        Engagement__c engObj = new Engagement__c(Name='Test EngageMent');
        insert engObj;
        return engObj;
    }

    public static Portfolio__c createPortfolio(String engagementId){
        
        Portfolio__c portObj = new Portfolio__c(Name='Test Portfolio',Engagement__c=engagementId);
        insert portObj;
        return portObj;
    }

    public static Product__c createProduct(String portId){
        
        Product__c productObj = new Product__c(Name='Test Product',Portfolio__c=portId);
        insert productObj;
        return productObj;
    }

    public static Epic__c createEpic(String productId){
        
        Epic__c epicObj = new Epic__c(Name='Test Epic',Product__c=productId);
        insert epicObj;
        return epicObj;
    }

    public static List<UserStory__c> createUserStories(String epicId, Integer noOfStories){

        List<UserStory__c> userStoryList = new List<UserStory__c>();
        for(Integer i = 0; i < noOfStories; i++) {
            UserStory__c userStory = new UserStory__c();
            userStory.Title__c = 'Test Title ' + i;
            userStory.User_Story__c = 'Test User Story ' + i;
            userStory.AcceptanceCriteria__c = 'Test Acceptance Criteria ' + i;
            userStory.Epic__c = epicId;
            userStoryList.add(userStory);
        }
        insert userStoryList;
        return userStoryList;
    }
    
    public static ConfigurationTable__c createConfigurationTable(){

        LLM__c llm = new LLM__c(Name='Test GPT', Model__c='Test Model', NameCred__c='TestCred');
        insert llm;
        PromptLibrary__c prompt = new PromptLibrary__c(Prompt__c='Test Prompts',Phase__c='Analysis',PromptType__c='Software Engineering');
        insert prompt;

        ConfigurationTable__c configTable = new ConfigurationTable__c();
        configTable.Name = 'Create User Story';
        configTable.LLM__c = llm.Id;
        configTable.PromptLibrary__c = prompt.Id;
        configTable.Phase__c = 'Analysis';
        insert configTable;
        return configTable;
    }
    
    public static Feedback__c createFeedback(){
        
        LLM__c llm = new LLM__c(Name='Test GPT', Model__c='Test Model', NameCred__c='TestCred');
        insert llm;
        PromptLibrary__c prompt = new PromptLibrary__c(Prompt__c='Test Prompts',Phase__c='Analysis',PromptType__c='Software Engineering');
        insert prompt;
        
        Feedback__c feedback = new Feedback__c();
        feedback.LLM__c = llm.Id;
        feedback.PromptLibrary__c = prompt.Id;
        insert feedback;
        return feedback;
    } 
    
        /*
    *********************************************************
    @Method Name     : insert_ComponentSpecAndJunctionRecord
    @author          : COE - Sachin
    @description     : Insert Component spec for user stories and create Junction Object
    @param inputType : user Story List and Formatted Component Spec (HTML)
    @return          : True if Dml insertion of records else false
    ********************************************************
    */ 
    
    public static Boolean insert_ComponentSpecAndJunctionRecord(List<UserStory__c> userStoryList, String formattedResponse){
        
        String relatedStories='';
        List<User_Stories_Component_Spec__c> usComSpecToUpdateList = New List<User_Stories_Component_Spec__c>();

        
        for(UserStory__c currentStory : userStoryList){
            relatedStories += currentStory.Name +'-'+currentStory.Title__c +';';
        }
        
        ComponentSpecification__c compSpec = new ComponentSpecification__c();
        compSpec.Related_User_Stories__c = relatedStories;
        compSpec.FormattedSpecification__c = formattedResponse;
        
        try{
            if(Schema.sObjectType.ComponentSpecification__c.isCreateable()) {
            insert compSpec;
            }
            
            for(UserStory__c currentStory : userStoryList){
                User_Stories_Component_Spec__c junctionObj = New User_Stories_Component_Spec__c();
                junctionObj.Component_Specification__c = compSpec.Id;
                junctionObj.User_Story__c = currentStory.Id;
                usComSpecToUpdateList.add(junctionObj);
            }
            if(usComSpecToUpdateList.size()>0 && Schema.sObjectType.User_Stories_Component_Spec__c.isCreateable()){
                Insert usComSpecToUpdateList;
                return true;
            }   
        }
        catch(Exception e){
            return false;
        }

        return false;
    }
}