force-app/main/default/objects/ComponentSpecification__c/ComponentSpecification__c.object-meta.xml
<CustomObject>
    <label>Component Specification</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Component Spec Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComponentSpecification__c/fields/FormattedSpecification__c.field-meta.xml
<CustomField>
    <fullName>FormattedSpecification__c</fullName>
    <label>Formatted Specification</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ComponentSpecification__c/fields/Related_User_Stories__c.field-meta.xml
<CustomField>
    <fullName>Related_User_Stories__c</fullName>
    <label>Related User Stories</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationTable__c/ConfigurationTable__c.object-meta.xml
<CustomObject>
    <label>Configuration Table</label>
    <nameField>
        <label>Configuration Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuration Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epic__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Portfolios</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/UserStory__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStory__c/fields/AcceptanceCriteria__c.field-meta.xml
<CustomField>
    <fullName>AcceptanceCriteria__c</fullName>
    <label>Acceptance Criteria</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserStory__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SDLC_AnalysisController_Test.cls
@isTest
private class SDLC_AnalysisController_Test {

    @testSetup
    static void setupTestData() {

        // Create test data for User Stories
        Engagement__c engObj = SDLC_TestDataFactory.createEngagement();
        Portfolio__c portObj = SDLC_TestDataFactory.createPortfolio(engObj.Id);
        Product__c productObj = SDLC_TestDataFactory.createProduct(portObj.Id);
        Epic__c epicObj = SDLC_TestDataFactory.createEpic(productObj.Id);
        List<UserStory__c> userStories = SDLC_TestDataFactory.createUserStories(epicObj.Id,5);
        ConfigurationTable__c config = SDLC_TestDataFactory.createConfigurationTable();
        // Create test data for Component Specifications
        List<ComponentSpecification__c> compSpecs = new List<ComponentSpecification__c>();
        String relatedStories='';
        for(Integer i = 0; i < userStories.size(); i++) {
            relatedStories +=userStories[i].Name+'-'+userStories[i].Title__c+';';
        }
        ComponentSpecification__c compSpec = new ComponentSpecification__c();
        compSpec.Related_User_Stories__c = relatedStories;
        compSpec.FormattedSpecification__c = 'Test Formatted Specification ';
        insert compSpec;
    }

    @isTest
    static void testInsertUserStories() {
        List<UserStory__c> userStories = [SELECT Id, Title__c, User_Story__c, AcceptanceCriteria__c FROM UserStory__c];
        String epicId = [Select Id FROM Epic__c][0].Id;

        List<SDLC_AnalysisController.UserStoryWrapper> userStoryWrappers = new List<SDLC_AnalysisController.UserStoryWrapper>();

        for(UserStory__c userStory : userStories) {
        SDLC_AnalysisController.UserStoryWrapper wrapper = new SDLC_AnalysisController.UserStoryWrapper();
            wrapper.title = userStory.Title__c;
            wrapper.userStory = userStory.User_Story__c;
            wrapper.acceptanceCriteria = userStory.AcceptanceCriteria__c;
            userStoryWrappers.add(wrapper);
        }

        Test.startTest();
        SDLC_AnalysisController.insertUserStories(userStoryWrappers, epicId);
        Test.stopTest();

        List<UserStory__c> insertedUserStories = [SELECT Id, Title__c, User_Story__c, AcceptanceCriteria__c, Epic__c FROM UserStory__c WHERE Epic__c = :epicId];
        System.assertEquals(userStories.size()+5, insertedUserStories.size());
        }

        @isTest
        static void testGetSavedUserStories() {
        List<UserStory__c> userStories = [SELECT Id, Title__c, User_Story__c, AcceptanceCriteria__c FROM UserStory__c];
        String epicId = [Select Id FROM Epic__c][0].Id;

        Test.startTest();
        List<SDLC_AnalysisController.UserStoryWrapper> savedUserStories = SDLC_AnalysisController.getSavedUserStories(epicId);
        Test.stopTest();

        System.assertNotEquals(null, savedUserStories);
    }

    // @isTest
    // static void testGetUserStoriesData() {
    //     List<UserStory__c> userStories = [SELECT Id, Name, Title__c FROM UserStory__c];
    //     String epicId = [Select Id from Epic__c][0].Id;

    //     Test.startTest();
    //     List<Map<String, Object>> userData = SDLC_AnalysisController.getUserStoriesData(epicId);
    //     Test.stopTest();

    //     System.assertNotEquals(null, userData);
    // }

    // @isTest
    // static void testFetchData() {
    //     Test.startTest();
    //     List<Map<String, Object>> data = SDLC_AnalysisController.fetchData();
    //     Test.stopTest();

    //     System.assertNotEquals(null, data);
    // }

    @isTest
    static void testGetConfigurationDetails() {
        Test.startTest();
        List<SDLC_AnalysisController.ConfigurationWrapper> configDetails = SDLC_AnalysisController.getConfigurationDetails('Analysis');
        Test.stopTest();

        System.assertNotEquals(null, configDetails);
    }
}